/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyRalliesRouteImport } from './routes/my-rallies'
import { Route as DotwellKnownAppleAppSiteAssociationRouteImport } from './routes/[.]well-known/apple-app-site-association'
import { Route as MCreatorTokenRouteImport } from './routes/m.$creatorToken'
import { Route as RInviteTokenRouteImport } from './routes/r.$inviteToken'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiPublicOgInviteTokenRouteImport } from './routes/api/public/og.$inviteToken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRalliesRoute = MyRalliesRouteImport.update({
  id: '/my-rallies',
  path: '/my-rallies',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAppleAppSiteAssociationRoute =
  DotwellKnownAppleAppSiteAssociationRouteImport.update({
    id: '/.well-known/apple-app-site-association',
    path: '/.well-known/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const MCreatorTokenRoute = MCreatorTokenRouteImport.update({
  id: '/m/$creatorToken',
  path: '/m/$creatorToken',
  getParentRoute: () => rootRouteImport,
} as any)
const RInviteTokenRoute = RInviteTokenRouteImport.update({
  id: '/r/$inviteToken',
  path: '/r/$inviteToken',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgInviteTokenRoute = ApiPublicOgInviteTokenRouteImport.update({
  id: '/api/public/og/$inviteToken',
  path: '/api/public/og/$inviteToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/my-rallies': typeof MyRalliesRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/m/$creatorToken': typeof MCreatorTokenRoute
  '/r/$inviteToken': typeof RInviteTokenRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/public/og/$inviteToken': typeof ApiPublicOgInviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/my-rallies': typeof MyRalliesRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/m/$creatorToken': typeof MCreatorTokenRoute
  '/r/$inviteToken': typeof RInviteTokenRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/public/og/$inviteToken': typeof ApiPublicOgInviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/my-rallies': typeof MyRalliesRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/m/$creatorToken': typeof MCreatorTokenRoute
  '/r/$inviteToken': typeof RInviteTokenRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/public/og/$inviteToken': typeof ApiPublicOgInviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/login'
    | '/my-rallies'
    | '/.well-known/apple-app-site-association'
    | '/m/$creatorToken'
    | '/r/$inviteToken'
    | '/api/v1/$'
    | '/api/public/og/$inviteToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/login'
    | '/my-rallies'
    | '/.well-known/apple-app-site-association'
    | '/m/$creatorToken'
    | '/r/$inviteToken'
    | '/api/v1/$'
    | '/api/public/og/$inviteToken'
  id:
    | '__root__'
    | '/'
    | '/llms.txt'
    | '/login'
    | '/my-rallies'
    | '/.well-known/apple-app-site-association'
    | '/m/$creatorToken'
    | '/r/$inviteToken'
    | '/api/v1/$'
    | '/api/public/og/$inviteToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  MyRalliesRoute: typeof MyRalliesRoute
  DotwellKnownAppleAppSiteAssociationRoute: typeof DotwellKnownAppleAppSiteAssociationRoute
  MCreatorTokenRoute: typeof MCreatorTokenRoute
  RInviteTokenRoute: typeof RInviteTokenRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiPublicOgInviteTokenRoute: typeof ApiPublicOgInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-rallies': {
      id: '/my-rallies'
      path: '/my-rallies'
      fullPath: '/my-rallies'
      preLoaderRoute: typeof MyRalliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/apple-app-site-association': {
      id: '/.well-known/apple-app-site-association'
      path: '/.well-known/apple-app-site-association'
      fullPath: '/.well-known/apple-app-site-association'
      preLoaderRoute: typeof DotwellKnownAppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$creatorToken': {
      id: '/m/$creatorToken'
      path: '/m/$creatorToken'
      fullPath: '/m/$creatorToken'
      preLoaderRoute: typeof MCreatorTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$inviteToken': {
      id: '/r/$inviteToken'
      path: '/r/$inviteToken'
      fullPath: '/r/$inviteToken'
      preLoaderRoute: typeof RInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/$inviteToken': {
      id: '/api/public/og/$inviteToken'
      path: '/api/public/og/$inviteToken'
      fullPath: '/api/public/og/$inviteToken'
      preLoaderRoute: typeof ApiPublicOgInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  MyRalliesRoute: MyRalliesRoute,
  DotwellKnownAppleAppSiteAssociationRoute:
    DotwellKnownAppleAppSiteAssociationRoute,
  MCreatorTokenRoute: MCreatorTokenRoute,
  RInviteTokenRoute: RInviteTokenRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiPublicOgInviteTokenRoute: ApiPublicOgInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
